version: '3.7'
services:
  mongodb:
    env_file:
      - .env-prod
    image: mongo:5.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db_shadown:/data/db
    networks:
       - app-network
  node:
    env_file:
      - .env-prod
    restart: always
    build: .
    environment:
      - DB_URL=${DB_URL}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_ID=${EMAIL_ID}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - ORIGIN=${ORIGIN}
      - NODE_ENV=production
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
      - S3_URL=${S3_URL}
      - S3_BUCKET=${S3_BUCKET}
      - TTWILLO_ACCOUNT_SID=${TTWILLO_ACCOUNT_SID}
      - TWILLO_AUTH_TOKEN=${TWILLO_AUTH_TOKEN}
    ports:
      - ${PORT}
    volumes:
      - ./:/code
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
    networks:
      - app-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node
    ports:
      - "80:80"
    networks:
      - app-network
volumes:
  db_shadown:
networks:
  app-network:
    driver: bridge
